openapi: '3.0.3'
info:
  title: Katalog API
  version: '1.0'
  contact:
    email: test@test.com
    name: Otto Franz
    url: irgendwas.com
  description: Eine tolle API
servers:
  - url: http://localhost:50001
paths:  
  /articles:
      get:
        tags:
          - Shop
        summary: Gebe alle Artikel zurück
        description: Es werden alle Artikel zurückgegeben
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/ArtikelResponse'
      post:
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArtikelRequest'
        tags:
          - Shop
        summary: Erstelle einen Artikel
        description: | 
          # Ein *Artikel* wird erstellt.

          ## Ein Artikel besteht aus den Feldern:
              - name
              - preis

          Inline-style: 
          ![alt text](https://kinsta.com/wp-content/uploads/2022/09/rest.png "Logo Title Text 1")

          | Tables        | Are           | PUT  |
          | ------------- |:-------------:| -----:|
          | /articles/id     | right-aligned | Objekt wird ersetzt |
          | col 2 is      | centered      |   $12 |
          | zebra stripes | are neat      |    $1 |

        responses:
          '201':
            description: Created
            headers:
              Location:
                description: URI des neuen Artikels
                schema:
                  type: string
                  maxLength: 500
                  format: uri
                  example: '407e197f-0e00-4b1b-942b-c4ad25c13c94'
            content:
              application/json:
                schema:                  
                  $ref: '#/components/schemas/ArtikelResponse'
  /articles/{aid}:
    parameters:
      - in: path
        name: aid        
        schema:
          type: string
        required: true
    get:
      tags:
        - Shop
        - Article Details
      summary: Gebe einen Artikel zurück
      description: Es wird ein Artikel zurückgegeben
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:                 
                $ref: '#/components/schemas/ArtikelResponse'
    put:
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArtikelRequest'
      tags:
        - Shop
        - Article Details
      summary: Ersetze einen Artikel 
      description: Ein Artikel wird ersetzt
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:                 
                $ref: '#/components/schemas/ArtikelResponse'
    delete:
      tags:
        - Shop
        - Article Details
      summary: Ein Artikel wird gelöscht
      description: Es wird ein Artikel gelöscht
      responses:
        '200':
          description: OK

components:
  schemas:
    ArtikelRequest:
      type: object
      properties:
        id:
          type: string
          maxLength: 36
          format: uuid
          example: '407e197f-0e00-4b1b-942b-c4ad25c13c94'
        name:
          type: string
          maxLength: 100
          example: 'Grapefruit'
          description: Das ist die Bezeichnung eines Artikels.
        preis:
          type: number
          minimum: 0
          example: 3.99
          description: Der Preis des Artikels.
      required:        
        - name
        - preis
    ArtikelResponse:
      type: object
      properties:
        id:
          type: string
          maxLength: 36
          format: uuid
          example: '407e197f-0e00-4b1b-942b-c4ad25c13c94'
        name:
          type: string
          maxLength: 100
          example: 'Grapefruit'
          description: Das ist die Bezeichnung eines Artikels.
        preis:
          type: number
          minimum: 0
          example: 3.99
          description: Der Preis des Artikels.
      required:
        - id    
        - name
        - preis

